version: '3' #'2.4' # 3.8

services:
  ros-realsense:
    container_name: ros-realsense
    build: ./build
    network_mode: host
    privileged: true
    devices:
      - "/dev:/dev"
    environment:
      - ROS_MASTER_URI=http://10.20.0.1:11311
      - ROS_IP=10.20.1.133 # $ hostname -I
    
    # launch and immediately disable the camera
    command: bash -c "(sleep 10 && rosservice call /realsense/enable False) & roslaunch realsense2_camera rs_camera_and_aruco.launch align_depth:=true enable_sync:=true camera:=realsense enable:=false"
    
    # for pointcloud use:
    # filters:=pointcloud
    # to get nice colorized output, use:
    # filters:=pointcloud,colorizer

    # this causes crashing:
    # initial_reset:=true
    
    restart: "no"
